language: r
warnings_are_errors: true
cache: packages

env:
  global:
    - R_CHECK_ARGS="--no-manual --as-cran"

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      before_deploy:
        - Rscript -e 'remotes::install_github("lockedatapublished/lockedatapkg")'
        - Rscript -e 'install.packages("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
        skip_cleanup: true
    - os: linux
      r: devel
    - os: osx
      r: release
      fortran: false


addons:
  apt:
    packages:
      - libssl1.0.0
r_packages:
  - covr
  - lintr
after_script:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
after_success:
  - Rscript -e 'covr::coveralls()'

stages:
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master
